project:
  type: website
  output-dir: "."
  execute-dir: project
  render:
    - "**/*.qmd"
    - "!analysis/Registration_whole_slide.qmd"
    - "!analysis/Registration_whole_slide_test.qmd"
    - "!analysis/02_transformation.qmd"
    - "!analysis/03_validation.qmd"
    - "!analysis/Col_registration.qmd"
    - "!analysis/Sarc_registration.qmd"
  resources:
    - images/

website:
  title: "XeniumAlign"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Overview"
      - icon: github
        href: https://github.com/leohermet1/xenium_align
  
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Documentation"
        contents:
          - text: "Toolkit Overview"
            href: index.qmd
      - section: "Tutorials"
        contents:
          - text: "1. Registration on toy dataset"
            href: analysis/01_ToyDataset.qmd
          - text: "2. Registration on whole slide"
            href: analysis/02_WholeSlide.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: show